FROM python:3.10
RUN echo 'Build is launched'
RUN echo 'Build next step'
RUN pip install streamlit

EXPOSE 8501
COPY app.py /tmp/

ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} sysadmin2 && \
    useradd gleb -u ${UID} -g ${GID} -m -s /bin/bash

USER gleb

WORKDIR /home/gleb

CMD ["streamlit", "run", "--server.port" ,"8501", "/tmp/app.py"]